# Site settings
title: Book Cover Generator
email: boilerplate@degeist.com
description: > # this means to ignore newlines until "baseurl:"
  Donec id justo. Curabitur ullamcorper ultricies nisi. Aenean tellus metus, bibendum sed, posuere ac, mattis non, nunc
twitter_description: In ut quam vitae odio lacinia tincidunt. Pellentesque posuere
baseurl: /page # "" in development. For Github
url: "http://degeist.com/" # the base hostname & protocol for your site
name: De Geist
twitter_username: degeist
facebook_username: degeist


# Build settings
markdown: redcarpet
highlighter: rouge # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
